"""add about me field to user table

Revision ID: 33c54ddc557a
Revises: 1a391246b1e5
Create Date: 2015-05-18 10:59:04.320650

"""

# revision identifiers, used by Alembic.
revision = '33c54ddc557a'
down_revision = '1a391246b1e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user',sa.Column('about_me', sa.VARCHAR(length=120)))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
