"""add about me field to user table

Revision ID: 4864575a8ef9
Revises: cb1b606509
Create Date: 2015-05-18 12:04:07.215364

"""

# revision identifiers, used by Alembic.
revision = '4864575a8ef9'
down_revision = 'cb1b606509'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user',sa.Column('about_me', sa.VARCHAR(length=120)))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
